//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.PROJECTINFOes = new HashSet<PROJECTINFO>();
        }
    
        public int accID { get; set; }
        public string userName { get; set; }
        public string passWords { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string emailBackup1 { get; set; }
        public string emailBackup2 { get; set; }
        public string zaloLink { get; set; }
        public Nullable<int> session { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTINFO> PROJECTINFOes { get; set; }
    }
}
