//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTINFO
    {
        public int projectInfoID { get; set; }
        public string projectName { get; set; }
        public string images { get; set; }
        public string video { get; set; }
        public string investor { get; set; }
        public string supplier { get; set; }
        public Nullable<int> typeOfProjectID { get; set; }
        public Nullable<int> investID { get; set; }
        public Nullable<int> familyID { get; set; }
        public Nullable<int> utilitiesID { get; set; }
        public Nullable<int> entertainmentID { get; set; }
        public Nullable<int> eventID { get; set; }
        public Nullable<int> productInfoID { get; set; }
        public Nullable<int> accID { get; set; }
        public string descirption { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ENTERTAINMENT ENTERTAINMENT { get; set; }
        public virtual EVENT EVENT { get; set; }
        public virtual FAMILY FAMILY { get; set; }
        public virtual INVEST INVEST { get; set; }
        public virtual PRODUCTINFO PRODUCTINFO { get; set; }
        public virtual TYPEOFPROJECT TYPEOFPROJECT { get; set; }
        public virtual UTILITy UTILITy { get; set; }
    }
}
