//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ENTERTAINMENT> ENTERTAINMENTs { get; set; }
        public virtual DbSet<EVENT> EVENTs { get; set; }
        public virtual DbSet<FAMILY> FAMILies { get; set; }
        public virtual DbSet<INVEST> INVESTs { get; set; }
        public virtual DbSet<PRODUCTDETAIL> PRODUCTDETAILs { get; set; }
        public virtual DbSet<PRODUCTINFO> PRODUCTINFOes { get; set; }
        public virtual DbSet<PROJECTINFO> PROJECTINFOes { get; set; }
        public virtual DbSet<STAGE> STAGEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TYPEOFPROJECT> TYPEOFPROJECTs { get; set; }
        public virtual DbSet<UTILITy> UTILITIES { get; set; }
    }
}
