//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEOFPROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPEOFPROJECT()
        {
            this.PROJECTINFOes = new HashSet<PROJECTINFO>();
        }
    
        public int typeOfProjectID { get; set; }
        public Nullable<int> productInfoID { get; set; }
        public Nullable<int> stageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTINFO> PROJECTINFOes { get; set; }
    }
}
